# Generated by Django 3.2.5 on 2021-07-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='UserData',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
